site_name: FastCRUDAPI
site_description: Easy way to generate crud apis for models.
site_url: 
theme:
  name: material
  palette:
  - scheme: default
    primary: orange
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: orange
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  logo: img/logo.drawio.png
  favicon: img/favicon.png
  language: en
repo_name: lpthong90/fastcrudapi
repo_url: https://github.com/lpthong90/fastcrudapi
edit_uri: ''
nav:
  - FastCRUDAPI: index.md